#!/bin/sh

start() {
    echo "Starting Projector"
    /opt/shell/autorun.sh &
}

stop() {
    echo "Stopping Projector"
    killall autorun.sh python3
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

